modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3 "
issueTrackerURL="https://github.com/aschmois/Avocado-Refill/issues"
[[mods]]
modId="avocadorefill"
version="${file.jarVersion}"
displayName="Avocado Refill"
updateJSONURL="https://raw.githubusercontent.com/aschmois/Avocado-Refill/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avocado-refill-forge/files"
logoFile="avocadorefill.png"
authors="aschmois"
description='''
Automatically refill your items when you use them from your hotbar or armor slots
'''
[[dependencies.avocadorefill]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.avocadorefill]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.schmoismods]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.schmoismods]]
    modId="sophisticatedbackpacks"
    mandatory=false
    versionRange="[1.19.2:11.3.0.262,)"
    ordering="AFTER"
    side="BOTH"