modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3 "
issueTrackerURL="https://github.com/aschmois/Avocado-Refill/issues"
[[mods]]
modId="avocadorefill"
version="${file.jarVersion}"
displayName="Avocado Refill"
updateJSONURL="https://github.com/aschmois/Avocado-Refill/blob/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/avocado-refill-forge/files"
logoFile="avocadorefill.png"
authors="aschmois"
description='''
Automatically refill your items when you use them from your hotbar or armor slots
'''
[[dependencies.avocadorefill]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.avocadorefill]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
[[dependencies.schmoismods]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.1-5.0.5.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.schmoismods]]
    modId="sophisticatedbackpacks"
    mandatory=false
    versionRange="[1.18.1-3.15.15.550,)"
    ordering="AFTER"
    side="BOTH"